spring:
  data:
    mongodb:
      uri: mongodb+srv://rvsinghs5330:A40Pzw3p0zYctUQT@cluster0.plb8qet.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8080