spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: rv.singh.s.5330@gmail.com
    password: mwqu pqhr anng nmba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  data:
    redis:
      host: redis-15199.crce182.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 15199
      password: ENfpj9KnlIJIydEdxqq2rKT9lhVpoBB5


weatherApiKey: "c267c354194cc1aae3ca0c50866b4a86"
